name: Fetch and Transform Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch_transform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up shell permissions
      run: chmod +x ./fetch_data.sh ./transform_data.sh

    - name: Run fetch_data.sh
      run: ./fetch_data.sh

    - name: Run transform_data.sh
      run: ./transform_data.sh

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Add & commit
      run: |
        git add raw_data/ processed_data/
        git commit -m "Update data files" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
